# Generated by Django 4.1.1 on 2022-10-18 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pertsona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kotxea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeloa', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=255)),
                ('pertsona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alokairu.pertsona')),
            ],
        ),
    ]
